language: generic

sudo: required
services:
  - docker

before install:
  - docker build -t jonny321/multidocker -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jonny321/multidocker npm test

after_success:
  - docker build -t jonny321/multi-client ./client
  - docker build -t jonny321/multi-nginx ./nginx
  - docker build -t jonny321/multi-server ./server
  - docker build -t jonny321/multi-worker ./worker
  # log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and push them to docker hub
  - docker push jonny321/multi-client
  - docker push jonny321/multi-nginx
  - docker push jonny321/multi-server
  - docker push jonny321/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'multi-docker'
  env: 'MultiDocker-env-1'
  bucket_name: 'elasticbeanstalk-us-east-2-510767167582'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY  


