langauge: javascript

sudo: required
services:
  - docker

before install:
  - docker build -t jonny321/multidocker -f ./client/Dockerfile.dev ./client

  script:
  - docker run -e CI=true jonny321/multidocker npm test

after_success:
  - docker build -t jonny321/multi-client ./client
  - docker build -t jonny321/multi-nginx ./nginx
  - docker build -t jonny321/multi-server ./server
  - docker build -t jonny321/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "DOCKER_ID" --password-stndin
  - docker push jonny321/multi-client
  - docker push jonny321/multi-nginx
  - docker push jonny321/multi-server
  - docker push jonny321/multi-worker


